#!/bin/bash

revision_msm8226=LA.BF.1.1.1.c5
revision_msm8974=LA.BF.1.1.1.c4
revision_newest=LA.BF.1.1.1.c5

function extract_falcon() {
    for FILE in `egrep -v '(^#|^$)' $1`; do
        OLDIFS=$IFS IFS=":" PARSING_ARRAY=($FILE) IFS=$OLDIFS
        FILE=`echo ${PARSING_ARRAY[0]} | sed -e "s/^-//g"`
        DEST=${PARSING_ARRAY[1]}
        if [ -z $DEST ]; then
            DEST=$FILE
        fi
	cd /home/louis/Dev/PARADOX_FALCON/
	cd $FILE
	git fetch aosparadox $revision_msm8226
	git fetch aosparadox lollipop_falcon
	git branch -D lollipop_falcon
	git checkout -b lollipop_falcon aosparadox/lollipop_falcon
	git merge aosparadox/$revision_msm8226
	git mergetool
	git commit -a
	git push aosparadox lollipop_falcon
	cd /home/louis/Dev/PARADOX_FALCON/
    done
}

function extract_msm8226() {
    for FILE in `egrep -v '(^#|^$)' $1`; do
        OLDIFS=$IFS IFS=":" PARSING_ARRAY=($FILE) IFS=$OLDIFS
        FILE=`echo ${PARSING_ARRAY[0]} | sed -e "s/^-//g"`
        DEST=${PARSING_ARRAY[1]}
        if [ -z $DEST ]; then
            DEST=$FILE
        fi
	cd /home/louis/Dev/PARADOX_FALCON/
	cd $FILE
	git fetch aosparadox $revision_msm8226
	git fetch aosparadox lollipop_msm8226
	git branch -D lollipop_msm8226
	git checkout -b lollipop_msm8226 aosparadox/lollipop_msm8226
	git merge aosparadox/$revision_msm8226
	git mergetool
	git commit -a
	git push aosparadox lollipop_msm8226
	cd /home/louis/Dev/PARADOX_FALCON/
    done
}

function extract_bacon() {
    for FILE in `egrep -v '(^#|^$)' $1`; do
        OLDIFS=$IFS IFS=":" PARSING_ARRAY=($FILE) IFS=$OLDIFS
        FILE=`echo ${PARSING_ARRAY[0]} | sed -e "s/^-//g"`
        DEST=${PARSING_ARRAY[1]}
        if [ -z $DEST ]; then
            DEST=$FILE
        fi
	cd /home/louis/Dev/PARADOX_BACON/
	cd $FILE
	git fetch aosparadox $revision_msm8974
	git fetch aosparadox lollipop_bacon
	git branch -D lollipop_bacon
	git checkout -b lollipop_bacon aosparadox/lollipop_bacon
	git merge aosparadox/$revision_msm8974
	git mergetool
	git commit -a
	git push aosparadox lollipop_bacon
	cd /home/louis/Dev/PARADOX_BACON/
    done
}

function extract_msm8974() {
    for FILE in `egrep -v '(^#|^$)' $1`; do
        OLDIFS=$IFS IFS=":" PARSING_ARRAY=($FILE) IFS=$OLDIFS
        FILE=`echo ${PARSING_ARRAY[0]} | sed -e "s/^-//g"`
        DEST=${PARSING_ARRAY[1]}
        if [ -z $DEST ]; then
            DEST=$FILE
        fi
	cd /home/louis/Dev/PARADOX_BACON/
	cd $FILE
	git fetch aosparadox $revision_msm8974
	git fetch aosparadox lollipop_msm8974
	git branch -D lollipop_msm8974
	git checkout -b lollipop_msm8974 aosparadox/lollipop_msm8974
	git merge aosparadox/$revision_msm8974
	git mergetool
	git commit -a
	git push aosparadox lollipop_msm8974
	cd /home/louis/Dev/PARADOX_BACON/
    done
}

function extract_common() {
    for FILE in `egrep -v '(^#|^$)' $1`; do
        OLDIFS=$IFS IFS=":" PARSING_ARRAY=($FILE) IFS=$OLDIFS
        FILE=`echo ${PARSING_ARRAY[0]} | sed -e "s/^-//g"`
        DEST=${PARSING_ARRAY[1]}
        if [ -z $DEST ]; then
            DEST=$FILE
        fi
	cd /home/louis/Dev/PARADOX_FALCON/
	cd $FILE
	git fetch aosparadox $revision_newest
	git fetch aosparadox lollipop_common
	git branch -D lollipop_common
	git checkout -b lollipop_common aosparadox/lollipop_common
	git merge aosparadox/$revision_newest
	git mergetool
	git commit -a
	git push aosparadox lollipop_common
	cd /home/louis/Dev/PARADOX_FALCON/
    done
}
extract_falcon /home/louis/Dev/local_aosparadox/UPDATE/lollipop_falcon
extract_msm8226 /home/louis/Dev/local_aosparadox/UPDATE/lollipop_msm8226
extract_bacon /home/louis/Dev/local_aosparadox/UPDATE/lollipop_bacon
extract_msm8974 /home/louis/Dev/local_aosparadox/UPDATE/lollipop_msm8974
extract_common /home/louis/Dev/local_aosparadox/UPDATE/lollipop_common
